export const SIGNIN_USER_OTP = 'SIGNIN_USER_OTP';
export const SIGNIN_USER_OTP_VERIFY = 'SIGNIN_USER_OTP_VERIFY';
export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_VERIFY = 'OTP_VERIFY';
export const OTP_SIGNUP = 'OTP_SIGNUP';
export const OTP_FULL_DATA = 'OTP_FULL_DATA';
