export const CURRENT_ACTIVE_PACKAGE = 'CURRENT_ACTIVE_PACKAGE';
export const GET_CURRENT_ACTIVE_PACKAGE = 'GET_CURRENT_ACTIVE_PACKAGE';
export const REMOVE_CURRENT_ACTIVE_PACKAGE = 'REMOVE_CURRENT_ACTIVE_PACKAGE';
export const CAMPAGIN_CODE_CHANGED = 'CAMPAGIN_CODE_CHANGED';
export const ACC_CHARGED_CHANGED = 'ACC_CHARGED_CHANGED';
